### ISSUE TITLE
Missing classname in ingress config file

### ISSUE THREAD

**Issue by rmarquis** [swiss-ai-center/text-recognition-ocr-service#1]
The `kubernetes/ingress.yml` is incomplete. It misses the `ingressClassName` parameter, so it cannot be accessed from the interface correctly.

```
spec:
  ingressClassName: nginx
  rules:
```
(add the middle line in the file)

**Comment by rmarquis** [comment]
@JunodCharlie

There is some config issue which prevents the pods to be accessible (thanks for the information, Glitchtip). I don't have access to the repo so I can't fix the issue by myself.

**Comment by JunodCharlie** [comment]
Thanks @rmarquis ! I'm just getting into the project, I appreciate the pointer.

**Comment by rmarquis** [comment]
FYI: This settings was lacking in the default service templates. This has now been fixed.
